### ISSUE TITLE
タイトルとナビゲーションバーがページによって異なる。

### ISSUE THREAD

**Issue by nkiib** [Minamin1234/minamin1234.github.io#1]
タイトルヘッダーとナビゲーションバーがインデックスページとエントリページで異なります。Why?

![image](https://github.com/Minamin1234/minamin1234.github.io/assets/48525357/75ecf369-d478-4aff-82f2-96f4ae01399b)

![image](https://github.com/Minamin1234/minamin1234.github.io/assets/48525357/9f367421-2be9-41fa-a13b-dd60058666b9)

**Comment by Minamin1234** [comment]
あー、単純にブログのやつ変えるの忘れてました。指摘感謝
(CMSにするべきだよなぁ)
